fix VIP missing on map
ehrenamtskarte/ehrenamtskarte pull request #196
Opened 2021-01-21 19:22 UTC by elKei24

2021-01-23 10:27 UTC, maxammann requested changes
Did you ask him whether he is fine with that? :sweat_smile:

2021-01-23 11:52 UTC, elKei24 commented
Of course not 😅

2021-01-23 13:59 UTC, RoAnBu commented
:joy:

2021-01-28 10:57 UTC, aiquita approved these changes

2021-01-28 10:57 UTC, aiquita commented on docker/reverse_proxy/www/sprites/osm-liberty.json
> +  "knappo": {
Ohh, ich bin großer Fan :)

2021-02-06 11:04 UTC, elKei24 commented
@maxammann face now consists of 8×8 pixels and I added a matte, so I think we are safe now

2021-02-19 18:10 UTC, closed without merging