#189: Base64 decode totpSecret
ehrenamtskarte/ehrenamtskarte pull request #214
Opened 2021-01-29 02:06 UTC by Schedulaar

Bytearrays should not be transmitted using actual arrays of numbers, as this would result in a query like
```[0, 1, 5, 2, 7, 2, 4, 3]```.
Instead, we simply base64 encode it.

2021-01-31 13:57 UTC, maxammann requested changes
Wong branch name

2021-01-31 14:41 UTC, maxammann approved these changes

2021-01-31 15:55 UTC, maxammann approved these changes

2021-01-31 16:00 UTC, maxammann commented on backend/src/main/kotlin/app/ehrenamtskarte/backend/verification/service/CardVerifier.kt
> +const val TOTP_LENGTH = 6
We use 6 as 10 is out of range. Actually we could use any value in range here security wise.

2021-02-01 16:28 UTC, RoAnBu approved these changes

2021-02-01 18:57 UTC, elKei24 approved these changes

2021-02-01 23:44 UTC, merged